# Generated by Django 5.1 on 2024-10-06 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 6, 14, 28, 12, 383422, tzinfo=datetime.timezone.utc)),
        ),
    ]
